# functions/pdf_converter.py
import io
from weasyprint import HTML
import datetime

def generate_tech_pdf(report_title: str, metrics: dict) -> io.BytesIO:
    """
    Generates a technical PDF report containing the project summary and 
    metrics, WITHOUT static images to avoid the kaleido dependency.
    """
    current_date = datetime.date.today().strftime("%d.%m.%Y")
    
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <style>
        @page {{ size: A4; margin: 20mm; background-color: #ffffff; }}
        body {{ font-family: Arial, sans-serif; color: #333; line-height: 1.5; }}
        .header {{ border-bottom: 2px solid #1a5276; padding-bottom: 10px; margin-bottom: 20px; }}
        .brand {{ float: right; font-size: 22pt; font-weight: bold; color: #1a5276; }}
        .title {{ font-size: 18pt; font-weight: bold; }}
        .summary {{ background: #f4f6f7; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ text-align: left; padding: 10px; border-bottom: 1px solid #eee; }}
        th {{ background: #f8f9fa; font-size: 10pt; text-transform: uppercase; }}
        .footer {{ position: fixed; bottom: 0; width: 100%; font-size: 8pt; color: #999; text-align: center; }}
        .notice {{ color: #e67e22; font-size: 9pt; margin-top: 20px; font-style: italic; }}
    </style>
    </head>
    <body>
        <div class="header">
            <div class="brand">DracBW</div>
            <div class="title">{report_title}</div>
            <p>Analysis Date: {current_date}</p>
        </div>

        <div class="summary">
            <strong>Executive Technical Summary:</strong><br>
            This report evaluates the energy consumption profile and simulates a Battery Energy Storage System (BESS) 
            to maintain a grid limit of {metrics['grid_limit']} kW.
        </div>

        <h2>Technical Requirements</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            <tr><td>Original Peak Load</td><td>{metrics['peak_raw']:.2f} kW</td></tr>
            <tr><td>Target Grid Limit</td><td>{metrics['grid_limit']:.2f} kW</td></tr>
            <tr><td>Required BESS Power (Inverter)</td><td>{metrics['min_pwr']:.2f} kW</td></tr>
            <tr><td>Required BESS Capacity (Storage)</td><td>{metrics['min_cap']:.2f} kWh</td></tr>
        </table>
        
        <p class="notice">* Note: Load profile charts have been omitted in this version.</p>

        <div class="footer">Generated by DracBW Energy Simulator</div>
    </body>
    </html>
    """
    
    pdf_buffer = io.BytesIO()
    HTML(string=html_template).write_pdf(pdf_buffer)
    pdf_buffer.seek(0)
    return pdf_buffer